import init, { ActionsRouter } from "../wasm/actions_router/actions_router.js";
import { 
    ADD_POINT_MESSAGE_HEADER, UPDATE_POINT_MESSAGE_HEADER, DELETE_POINT_MESSAGE_HEADER, RESTORE_POINT_MESSAGE_HEADER,

    ADD_LINE_MESSAGE_HEADER, UPDATE_LINE_MESSAGE_HEADER, DELETE_LINE_MESSAGE_HEADER, RESTORE_LINE_MESSAGE_HEADER,

    ADD_SURFACE_MESSAGE_HEADER, UPDATE_SURFACE_MESSAGE_HEADER, ROTATE_SURFACE_VERTICES_CLOCKWISE_MESSAGE_HEADER,
    ROTATE_SURFACE_VERTICES_COUNTER_CLOCKWISE_MESSAGE_HEADER, FLIP_SURFACE_NORMAL_AXIS_MESSAGE_HEADER,
    DELETE_SURFACE_MESSAGE_HEADER, RESTORE_SURFACE_MESSAGE_HEADER,

    ADD_MATERIAL_MESSAGE_HEADER, UPDATE_MATERIAL_MESSAGE_HEADER, DELETE_MATERIAL_MESSAGE_HEADER,
    RESTORE_MATERIAL_MESSAGE_HEADER,

    ADD_TRUSS_SECTION_MESSAGE_HEADER, UPDATE_TRUSS_SECTION_MESSAGE_HEADER, DELETE_TRUSS_SECTION_MESSAGE_HEADER,
    RESTORE_TRUSS_SECTION_MESSAGE_HEADER,

    ADD_BEAM_SECTION_MESSAGE_HEADER, UPDATE_BEAM_SECTION_MESSAGE_HEADER, DELETE_BEAM_SECTION_MESSAGE_HEADER,
    RESTORE_BEAM_SECTION_MESSAGE_HEADER,

    ADD_PLATE_SECTION_MESSAGE_HEADER, UPDATE_PLATE_SECTION_MESSAGE_HEADER, DELETE_PLATE_SECTION_MESSAGE_HEADER,
    RESTORE_PLATE_SECTION_MESSAGE_HEADER,

    ADD_PROPERTIES_MESSAGE_HEADER , UPDATE_PROPERTIES_MESSAGE_HEADER, DELETE_PROPERTIES_MESSAGE_HEADER,
    RESTORE_PROPERTIES_MESSAGE_HEADER,

    ASSIGN_PROPERTIES_TO_LINES_MESSAGE_HEADER,

    ADD_BEAM_SECTION_LOCAL_AXIS_1_DIRECTION_MESSAGE_HEADER, DELETE_BEAM_SECTION_LOCAL_AXIS_1_DIRECTION_MESSAGE_HEADER,
    ASSIGN_BEAM_SECTION_LOCAL_AXIS_1_DIRECTION_MESSAGE_HEADER, RESTORE_BEAM_SECTION_LOCAL_AXIS_1_DIRECTION_MESSAGE_HEADER,

    ASSIGN_PROPERTIES_TO_SURFACES_MESSAGE_HEADER,

    ADD_CONCENTRATED_LOAD_MESSAGE_HEADER, UPDATE_CONCENTRATED_LOAD_MESSAGE_HEADER,
    DELETE_CONCENTRATED_LOAD_MESSAGE_HEADER, RESTORE_CONCENTRATED_LOAD_MESSAGE_HEADER,

    ADD_UNIFORMLY_DISTRIBUTED_LINE_LOAD_MESSAGE_HEADER, UPDATE_UNIFORMLY_DISTRIBUTED_LINE_LOAD_MESSAGE_HEADER,
    DELETE_UNIFORMLY_DISTRIBUTED_LINE_LOAD_MESSAGE_HEADER, RESTORE_UNIFORMLY_DISTRIBUTED_LINE_LOAD_MESSAGE_HEADER,

    ADD_UNIFORMLY_DISTRIBUTED_SURFACE_LOAD_MESSAGE_HEADER, UPDATE_UNIFORMLY_DISTRIBUTED_SURFACE_LOAD_MESSAGE_HEADER,
    DELETE_UNIFORMLY_DISTRIBUTED_SURFACE_LOAD_MESSAGE_HEADER, RESTORE_UNIFORMLY_DISTRIBUTED_SURFACE_LOAD_MESSAGE_HEADER,

    ADD_POINT_BOUNDARY_CONDITION_MESSAGE_HEADER, UPDATE_POINT_BOUNDARY_CONDITION_MESSAGE_HEADER,
    DELETE_POINT_BOUNDARY_CONDITION_MESSAGE_HEADER, RESTORE_POINT_BOUNDARY_CONDITION_MESSAGE_HEADER,

    UPDATE_GLOBAL_MESH_SEED_MESSAGE_HEADER, UPDATE_LINES_MESH_SEED_MESSAGE_HEADER,
    UNDO_LINES_MESH_SEED_UPDATE_MESSAGE_HEADER, UPDATE_SURFACES_MESH_SEED_MESSAGE_HEADER,
    UNDO_SURFACES_MESH_SEED_UPDATE_MESSAGE_HEADER,
    
    UNDO_MESSAGE_HEADER, REDO_MESSAGE_HEADER,
} from "../consts/actions_router_consts.js";
import { 
    LOCAL_AXIS_1_DIRECTION_INPUT_INFO_MESSAGE_HEADER,

    MAX_POINT_NUMBER, MAX_LINE_NUMBER, MAX_SURFACE_NUMBER,
} from "../consts/common_consts.js";


export async function initializeActionsRouter() {
    await init();
    const actionsRouter = ActionsRouter.create(
        ADD_POINT_MESSAGE_HEADER,
        UPDATE_POINT_MESSAGE_HEADER,
        DELETE_POINT_MESSAGE_HEADER,
        RESTORE_POINT_MESSAGE_HEADER,

        ADD_LINE_MESSAGE_HEADER,
        UPDATE_LINE_MESSAGE_HEADER,
        DELETE_LINE_MESSAGE_HEADER,
        RESTORE_LINE_MESSAGE_HEADER,

        ADD_SURFACE_MESSAGE_HEADER,
        UPDATE_SURFACE_MESSAGE_HEADER,
        ROTATE_SURFACE_VERTICES_CLOCKWISE_MESSAGE_HEADER,
        ROTATE_SURFACE_VERTICES_COUNTER_CLOCKWISE_MESSAGE_HEADER,
        FLIP_SURFACE_NORMAL_AXIS_MESSAGE_HEADER,
        DELETE_SURFACE_MESSAGE_HEADER,
        RESTORE_SURFACE_MESSAGE_HEADER,

        ADD_MATERIAL_MESSAGE_HEADER,
        UPDATE_MATERIAL_MESSAGE_HEADER,
        DELETE_MATERIAL_MESSAGE_HEADER,
        RESTORE_MATERIAL_MESSAGE_HEADER,

        ADD_TRUSS_SECTION_MESSAGE_HEADER,
        UPDATE_TRUSS_SECTION_MESSAGE_HEADER,
        DELETE_TRUSS_SECTION_MESSAGE_HEADER,
        RESTORE_TRUSS_SECTION_MESSAGE_HEADER,

        ADD_BEAM_SECTION_MESSAGE_HEADER,
        UPDATE_BEAM_SECTION_MESSAGE_HEADER,
        DELETE_BEAM_SECTION_MESSAGE_HEADER,
        RESTORE_BEAM_SECTION_MESSAGE_HEADER,

        ADD_PLATE_SECTION_MESSAGE_HEADER,
        UPDATE_PLATE_SECTION_MESSAGE_HEADER,
        DELETE_PLATE_SECTION_MESSAGE_HEADER,
        RESTORE_PLATE_SECTION_MESSAGE_HEADER,

        ADD_PROPERTIES_MESSAGE_HEADER,
        UPDATE_PROPERTIES_MESSAGE_HEADER,
        DELETE_PROPERTIES_MESSAGE_HEADER,
        RESTORE_PROPERTIES_MESSAGE_HEADER,

        ASSIGN_PROPERTIES_TO_LINES_MESSAGE_HEADER,

        ADD_BEAM_SECTION_LOCAL_AXIS_1_DIRECTION_MESSAGE_HEADER,
        DELETE_BEAM_SECTION_LOCAL_AXIS_1_DIRECTION_MESSAGE_HEADER,
        ASSIGN_BEAM_SECTION_LOCAL_AXIS_1_DIRECTION_MESSAGE_HEADER,
        RESTORE_BEAM_SECTION_LOCAL_AXIS_1_DIRECTION_MESSAGE_HEADER,

        ASSIGN_PROPERTIES_TO_SURFACES_MESSAGE_HEADER,

        ADD_CONCENTRATED_LOAD_MESSAGE_HEADER,
        UPDATE_CONCENTRATED_LOAD_MESSAGE_HEADER,
        DELETE_CONCENTRATED_LOAD_MESSAGE_HEADER,
        RESTORE_CONCENTRATED_LOAD_MESSAGE_HEADER,

        ADD_UNIFORMLY_DISTRIBUTED_LINE_LOAD_MESSAGE_HEADER,
        UPDATE_UNIFORMLY_DISTRIBUTED_LINE_LOAD_MESSAGE_HEADER,
        DELETE_UNIFORMLY_DISTRIBUTED_LINE_LOAD_MESSAGE_HEADER,
        RESTORE_UNIFORMLY_DISTRIBUTED_LINE_LOAD_MESSAGE_HEADER,

        ADD_UNIFORMLY_DISTRIBUTED_SURFACE_LOAD_MESSAGE_HEADER,
        UPDATE_UNIFORMLY_DISTRIBUTED_SURFACE_LOAD_MESSAGE_HEADER,
        DELETE_UNIFORMLY_DISTRIBUTED_SURFACE_LOAD_MESSAGE_HEADER,
        RESTORE_UNIFORMLY_DISTRIBUTED_SURFACE_LOAD_MESSAGE_HEADER,

        ADD_POINT_BOUNDARY_CONDITION_MESSAGE_HEADER,
        UPDATE_POINT_BOUNDARY_CONDITION_MESSAGE_HEADER,
        DELETE_POINT_BOUNDARY_CONDITION_MESSAGE_HEADER,
        RESTORE_POINT_BOUNDARY_CONDITION_MESSAGE_HEADER,

        UPDATE_GLOBAL_MESH_SEED_MESSAGE_HEADER,

        UPDATE_LINES_MESH_SEED_MESSAGE_HEADER,
        UNDO_LINES_MESH_SEED_UPDATE_MESSAGE_HEADER,

        UPDATE_SURFACES_MESH_SEED_MESSAGE_HEADER,
        UNDO_SURFACES_MESH_SEED_UPDATE_MESSAGE_HEADER,

        UNDO_MESSAGE_HEADER,
        REDO_MESSAGE_HEADER,

        LOCAL_AXIS_1_DIRECTION_INPUT_INFO_MESSAGE_HEADER,

        MAX_POINT_NUMBER,
        MAX_LINE_NUMBER,
        MAX_SURFACE_NUMBER,
    );
    return actionsRouter;    
}
