import init, { Preprocessor } from "../wasm/preprocessor/preprocessor.js";
import { 
    REL_TOL, ABS_TOL, INIT_GLOBAL_MESH_SEED_VALUE, EVENT_TARGET, LOCAL_AXIS_1_DIRECTION_INPUT_INFO_MESSAGE_HEADER,
} from "../consts/common_consts.js";
import { 
    ADD_POINT_EVENT_NAME, UPDATE_POINT_EVENT_NAME, DELETE_POINT_EVENT_NAME,
    ADD_LINE_EVENT_NAME, UPDATE_LINE_EVENT_NAME, DELETE_LINE_EVENT_NAME,
    ADD_SURFACE_EVENT_NAME, UPDATE_SURFACE_EVENT_NAME, DELETE_SURFACE_EVENT_NAME,
    ADD_MATERIAL_EVENT_NAME, UPDATE_MATERIAL_EVENT_NAME, DELETE_MATERIAL_EVENT_NAME,
    ADD_TRUSS_SECTION_EVENT_NAME, UPDATE_TRUSS_SECTION_EVENT_NAME, DELETE_TRUSS_SECTION_EVENT_NAME,
    ADD_BEAM_SECTION_EVENT_NAME, UPDATE_BEAM_SECTION_EVENT_NAME, DELETE_BEAM_SECTION_EVENT_NAME,
    ADD_PLATE_SECTION_EVENT_NAME, UPDATE_PLATE_SECTION_EVENT_NAME, DELETE_PLATE_SECTION_EVENT_NAME,
    ADD_PROPERTIES_EVENT_NAME, UPDATE_PROPERTIES_EVENT_NAME, DELETE_PROPERTIES_EVENT_NAME,
    INCREASE_ACTION_ID_EVENT_NAME, ADD_BEAM_SECTION_LOCAL_AXIS_1_DIRECTION_EVENT_NAME,
    DELETE_BEAM_SECTION_LOCAL_AXIS_1_DIRECTION_EVENT_NAME, UPDATE_BEAM_SECTION_ORIENTATION_DATA_EVENT_NAME,
    ADD_CONCENTRATED_LOAD_EVENT_NAME, UPDATE_CONCENTRATED_LOAD_EVENT_NAME, DELETE_CONCENTRATED_LOAD_EVENT_NAME,
    ADD_POINT_BOUNDARY_CONDITION_EVENT_NAME, UPDATE_POINT_BOUNDARY_CONDITION_EVENT_NAME,
    DELETE_POINT_BOUNDARY_CONDITION_EVENT_NAME, UPDATE_GLOBAL_MESH_SEED_EVENT_NAME,
} from "../consts/preprocessor_consts.js";


export async function initializePreprocessor() {
    await init();
    const preprocessor = Preprocessor.create(
        REL_TOL,
        ABS_TOL,
        EVENT_TARGET,

        ADD_POINT_EVENT_NAME,
        UPDATE_POINT_EVENT_NAME,
        DELETE_POINT_EVENT_NAME,

        ADD_LINE_EVENT_NAME,
        UPDATE_LINE_EVENT_NAME,
        DELETE_LINE_EVENT_NAME,

        ADD_SURFACE_EVENT_NAME,
        UPDATE_SURFACE_EVENT_NAME,
        DELETE_SURFACE_EVENT_NAME,

        ADD_MATERIAL_EVENT_NAME,
        UPDATE_MATERIAL_EVENT_NAME,
        DELETE_MATERIAL_EVENT_NAME,

        ADD_TRUSS_SECTION_EVENT_NAME,
        UPDATE_TRUSS_SECTION_EVENT_NAME,
        DELETE_TRUSS_SECTION_EVENT_NAME,

        ADD_BEAM_SECTION_EVENT_NAME,
        UPDATE_BEAM_SECTION_EVENT_NAME,
        DELETE_BEAM_SECTION_EVENT_NAME,

        ADD_PLATE_SECTION_EVENT_NAME,
        UPDATE_PLATE_SECTION_EVENT_NAME,
        DELETE_PLATE_SECTION_EVENT_NAME,

        ADD_PROPERTIES_EVENT_NAME,
        UPDATE_PROPERTIES_EVENT_NAME,
        DELETE_PROPERTIES_EVENT_NAME,

        INCREASE_ACTION_ID_EVENT_NAME,

        ADD_BEAM_SECTION_LOCAL_AXIS_1_DIRECTION_EVENT_NAME,
        DELETE_BEAM_SECTION_LOCAL_AXIS_1_DIRECTION_EVENT_NAME,
        UPDATE_BEAM_SECTION_ORIENTATION_DATA_EVENT_NAME,

        LOCAL_AXIS_1_DIRECTION_INPUT_INFO_MESSAGE_HEADER,

        ADD_CONCENTRATED_LOAD_EVENT_NAME,
        UPDATE_CONCENTRATED_LOAD_EVENT_NAME,
        DELETE_CONCENTRATED_LOAD_EVENT_NAME,

        ADD_POINT_BOUNDARY_CONDITION_EVENT_NAME,
        UPDATE_POINT_BOUNDARY_CONDITION_EVENT_NAME,
        DELETE_POINT_BOUNDARY_CONDITION_EVENT_NAME,

        INIT_GLOBAL_MESH_SEED_VALUE,
        UPDATE_GLOBAL_MESH_SEED_EVENT_NAME,
    );
    return preprocessor;    
}
