use crate::functions::convert_slice_to_array;


pub struct Props
{
    pub abs_tol: f32,
    pub rel_tol: f32,

    pub init_cursor_coord_x: i32,
    pub init_cursor_coord_y: i32,
    pub init_theta: f32,
    pub init_phi: f32,
    pub init_dx: f32,
    pub init_dy: f32,
    pub init_d_scale: f32,
    pub init_is_point_visible: bool,
    pub init_is_line_visible: bool,
    pub init_is_surface_visible: bool,
    pub init_is_surface_edges_1_3_visible: bool,
    pub init_is_surface_edges_2_4_visible: bool,
    pub init_is_beam_section_orientation_visible: bool,
    pub init_is_surface_normal_visible: bool,
    pub init_is_load_visible: bool,
    pub init_is_boundary_condition_visible: bool,
    pub is_mesh_seed_visible: bool,

    pub init_is_node_visible: bool,
    pub init_is_truss_element_visible: bool,
    pub init_is_beam_element_visible: bool,
    pub init_is_plate_element_visible: bool,
    pub init_is_local_axes_visible: bool,

    pub cs_origin: [f32; 3],
    pub cs_axis_x: [f32; 3],
    pub cs_axis_x_color: [f32; 4],
    pub cs_axis_y: [f32; 3],
    pub cs_axis_y_color: [f32; 4],
    pub cs_axis_z: [f32; 3],
    pub cs_axis_z_color: [f32; 4],

    pub cs_axes_caps_height: f32,
    pub cs_axes_caps_width: f32,
    pub cs_axes_caps_base_points_number: u32,

    pub cs_axes_scale: f32,
    pub cs_axes_x_shift: f32,
    pub cs_axes_y_shift: f32,
    pub cs_axes_z_shift: f32,
    pub axis_x_denotation_shift_x: f32,
    pub axis_x_denotation_shift_y: f32,
    pub axis_y_denotation_shift_x: f32,
    pub axis_y_denotation_shift_y: f32,
    pub axis_z_denotation_shift_x: f32,
    pub axis_z_denotation_shift_y: f32,
    pub axis_z_denotation_shift_z: f32,
    pub canvas_axes_denotation_color: String,

    pub hint_shift_x: f32,
    pub rotation_hint_shift_y: f32,
    pub zoom_hint_shift_y: f32,
    pub pan_hint_shift_y: f32,
    pub hints_color: String,

    pub drawn_object_selected_color: [f32; 4],
    pub node_color: [f32; 4],
    pub point_color: [f32; 4],
    pub drawn_point_object_denotation_shift: f32,

    pub line_default_color: [f32; 4],
    pub line_truss_props_color: [f32; 4],
    pub line_beam_props_color: [f32; 4],
    pub element_color: [f32; 4],
    pub drawn_line_object_denotation_shift: f32,

    pub surface_default_color: [f32; 4],
    pub surface_plate_props_color: [f32; 4],

    pub selection_rectangle_stroke_color: String,
    pub selection_rectangle_fill_color: String, 

    pub event_target: String,
    pub selected_object_event_name: String,

    pub beam_section_orientation_line_length: f32,
    pub beam_section_orientation_cap_height: f32,
    pub beam_section_orientation_cap_width: f32,
    pub beam_section_orientation_cap_base_points_number: u32,
    pub beam_section_orientation_color: [f32; 4],

    pub surface_normal_line_length: f32,
    pub surface_normal_cap_height: f32,
    pub surface_normal_cap_width: f32,
    pub surface_normal_cap_base_points_number: u32,
    pub surface_normal_color: [f32; 4],

    pub concentrated_load_line_length: f32,
    pub concentrated_load_cap_height: f32,
    pub concentrated_load_cap_width: f32,
    pub concentrated_load_cap_base_points_number: u32,
    pub concentrated_load_color: [f32; 4],

    pub uniformly_distributed_line_load_line_length: f32,
    pub uniformly_distributed_line_load_cap_height: f32,
    pub uniformly_distributed_line_load_cap_width: f32,
    pub uniformly_distributed_line_load_cap_base_points_number: u32,
    pub uniformly_distributed_line_load_color: [f32; 4],
    pub number_of_uniformly_distributed_line_load_arrows: u32,

    pub uniformly_distributed_surface_load_line_length: f32,
    pub uniformly_distributed_surface_load_cap_height: f32,
    pub uniformly_distributed_surface_load_cap_width: f32,
    pub uniformly_distributed_surface_load_cap_base_points_number: u32,
    pub uniformly_distributed_surface_load_color: [f32; 4],
    pub number_of_uniformly_distributed_surface_load_arrows: u32,

    pub point_boundary_condition_cap_height: f32,
    pub point_boundary_condition_cap_width: f32,
    pub point_boundary_condition_cap_base_point_number: u32,
    pub point_boundary_condition_color: [f32; 4],

    pub global_mesh_seed_color: [f32; 4],
    pub local_mesh_seed_color: [f32; 4],

    pub symbols_min_line_length: f32,
    pub symbols_min_cap_height: f32,
    pub symbols_min_cap_width: f32,
    pub symbols_max_line_length: f32,
    pub symbols_max_cap_height: f32,
    pub symbols_max_cap_width: f32,
    pub symbols_cap_base_points_number: u32,

    pub color_bar_shift_x: f32,
    pub color_bar_y_bottom: f32,
    pub color_bar_y_top: f32,
    pub color_bar_width: f32,
    pub color_bar_min_color: [f32; 4],
    pub color_bar_max_color: [f32; 4],

    pub color_bar_caption_shift_x: f32,
    pub color_bar_caption_header_shift_y: f32,
    pub color_bar_caption_component_shift_y: f32,
    pub color_bar_caption_extreme_value_shift_x: f32,

    pub local_axis_line_length: f32,
    pub local_axis_cap_height: f32,
    pub local_axis_cap_width: f32,
    pub local_axis_cap_base_points_number: u32,
    pub local_axis_r_color: [f32; 4],
    pub local_axis_s_color: [f32; 4],
    pub local_axis_t_color: [f32; 4],

    pub plate_scale_for_load_arrows: f32,
}


impl Props
{
    pub(super) fn create(
        abs_tol: f32,
        rel_tol: f32,

        init_cursor_coord_x: i32,
        init_cursor_coord_y: i32,
        init_theta: f32,
        init_phi: f32,
        init_dx: f32,
        init_dy: f32,
        init_d_scale: f32,
        init_is_point_visible: bool,
        init_is_line_visible: bool,
        init_is_surface_visible: bool,
        init_is_surface_edges_1_3_visible: bool,
        init_is_surface_edges_2_4_visible: bool,
        init_is_beam_section_orientation_visible: bool,
        init_is_surface_normal_visible: bool,
        init_is_load_visible: bool,
        init_is_boundary_condition_visible: bool,
        is_mesh_seed_visible: bool,
    
        init_is_node_visible: bool,
        init_is_truss_element_visible: bool,
        init_is_beam_element_visible: bool,
        init_is_plate_element_visible: bool,
        init_is_local_axes_visible: bool,

        cs_origin: &[f32],
        cs_axis_x: &[f32],
        cs_axis_x_color: &[f32],
        cs_axis_y: &[f32],
        cs_axis_y_color: &[f32],
        cs_axis_z: &[f32],
        cs_axis_z_color: &[f32],

        cs_axes_caps_height: f32,
        cs_axes_caps_width: f32,
        cs_axes_caps_base_points_number: u32,

        cs_axes_scale: f32,
        cs_axes_x_shift: f32,
        cs_axes_y_shift: f32,
        cs_axes_z_shift: f32,
        axis_x_denotation_shift_x: f32,
        axis_x_denotation_shift_y: f32,
        axis_y_denotation_shift_x: f32,
        axis_y_denotation_shift_y: f32,
        axis_z_denotation_shift_x: f32,
        axis_z_denotation_shift_y: f32,
        axis_z_denotation_shift_z: f32,
        canvas_axes_denotation_color: &str,

        hint_shift_x: f32,
        rotation_hint_shift_y: f32,
        zoom_hint_shift_y: f32,
        pan_hint_shift_y: f32,
        hints_color: &str,

        drawn_object_selected_color: &[f32],
        node_color: &[f32],
        point_color: &[f32],
        drawn_point_object_denotation_shift: f32,

        line_default_color: &[f32],
        line_truss_props_color: &[f32],
        line_beam_props_color: &[f32],
        element_color: &[f32],
        drawn_line_object_denotation_shift: f32,

        surface_default_color: &[f32],
        surface_plate_props_color: &[f32],

        selection_rectangle_stroke_color: &str,
        selection_rectangle_fill_color: &str, 

        event_target: &str,
        selected_object_event_name: &str,        

        beam_section_orientation_line_length: f32,
        beam_section_orientation_cap_height: f32,
        beam_section_orientation_cap_width: f32,
        beam_section_orientation_cap_base_points_number: u32,
        beam_section_orientation_color: &[f32],

        surface_normal_line_length: f32,
        surface_normal_cap_height: f32,
        surface_normal_cap_width: f32,
        surface_normal_cap_base_points_number: u32,
        surface_normal_color: &[f32],

        concentrated_load_line_length: f32,
        concentrated_load_cap_height: f32,
        concentrated_load_cap_width: f32,
        concentrated_load_cap_base_points_number: u32,
        concentrated_load_color: &[f32],

        uniformly_distributed_line_load_line_length: f32,
        uniformly_distributed_line_load_cap_height: f32,
        uniformly_distributed_line_load_cap_width: f32,
        uniformly_distributed_line_load_cap_base_points_number: u32,
        uniformly_distributed_line_load_color: &[f32],
        number_of_uniformly_distributed_line_load_arrows: u32,

        uniformly_distributed_surface_load_line_length: f32,
        uniformly_distributed_surface_load_cap_height: f32,
        uniformly_distributed_surface_load_cap_width: f32,
        uniformly_distributed_surface_load_cap_base_points_number: u32,
        uniformly_distributed_surface_load_color: &[f32],
        number_of_uniformly_distributed_surface_load_arrows: u32,

        point_boundary_condition_cap_height: f32,
        point_boundary_condition_cap_width: f32,
        point_boundary_condition_cap_base_point_number: u32,
        point_boundary_condition_color: &[f32],

        global_mesh_seed_color: &[f32],
        local_mesh_seed_color: &[f32],

        symbols_min_line_length: f32,
        symbols_min_cap_height: f32,
        symbols_min_cap_width: f32,
        symbols_max_line_length: f32,
        symbols_max_cap_height: f32,
        symbols_max_cap_width: f32,
        symbols_cap_base_points_number: u32,

        color_bar_shift_x: f32,
        color_bar_y_bottom: f32,
        color_bar_y_top: f32,
        color_bar_width: f32,
        color_bar_min_color: &[f32],
        color_bar_max_color: &[f32],

        color_bar_caption_shift_x: f32,
        color_bar_caption_header_shift_y: f32,
        color_bar_caption_component_shift_y: f32,
        color_bar_caption_extreme_value_shift_x: f32,

        local_axis_line_length: f32,
        local_axis_cap_height: f32,
        local_axis_cap_width: f32,
        local_axis_cap_base_points_number: u32,
        local_axis_r_color: &[f32],
        local_axis_s_color: &[f32],
        local_axis_t_color: &[f32],

        plate_scale_for_load_arrows: f32,
    )
        -> Self
    {
        Props 
        { 
            abs_tol,
            rel_tol,

            init_cursor_coord_x,
            init_cursor_coord_y,
            init_theta,
            init_phi,
            init_dx,
            init_dy,
            init_d_scale,
            init_is_point_visible,
            init_is_line_visible,
            init_is_surface_visible,
            init_is_surface_edges_1_3_visible,
            init_is_surface_edges_2_4_visible,
            init_is_beam_section_orientation_visible,
            init_is_surface_normal_visible,
            init_is_load_visible,
            init_is_boundary_condition_visible,
            is_mesh_seed_visible,
        
            init_is_node_visible,
            init_is_truss_element_visible,
            init_is_beam_element_visible,
            init_is_plate_element_visible,
            init_is_local_axes_visible,

            cs_origin: convert_slice_to_array(cs_origin),
            cs_axis_x: convert_slice_to_array(cs_axis_x),
            cs_axis_x_color: convert_slice_to_array(cs_axis_x_color),
            cs_axis_y: convert_slice_to_array(cs_axis_y),
            cs_axis_y_color: convert_slice_to_array(cs_axis_y_color),
            cs_axis_z: convert_slice_to_array(cs_axis_z),
            cs_axis_z_color: convert_slice_to_array(cs_axis_z_color),

            cs_axes_caps_height,
            cs_axes_caps_width,
            cs_axes_caps_base_points_number,

            cs_axes_scale,
            cs_axes_x_shift,
            cs_axes_y_shift,
            cs_axes_z_shift,
            axis_x_denotation_shift_x,
            axis_x_denotation_shift_y,
            axis_y_denotation_shift_x,
            axis_y_denotation_shift_y,
            axis_z_denotation_shift_x,
            axis_z_denotation_shift_y,
            axis_z_denotation_shift_z,
            canvas_axes_denotation_color: canvas_axes_denotation_color.to_string(),

            hint_shift_x,
            rotation_hint_shift_y,
            zoom_hint_shift_y,
            pan_hint_shift_y,
            hints_color: hints_color.to_string(),

            drawn_object_selected_color: convert_slice_to_array(drawn_object_selected_color),
            node_color: convert_slice_to_array(node_color),
            point_color: convert_slice_to_array(point_color),
            drawn_point_object_denotation_shift,

            line_default_color: convert_slice_to_array(line_default_color),
            line_truss_props_color: convert_slice_to_array(line_truss_props_color),
            line_beam_props_color: convert_slice_to_array(line_beam_props_color),
            element_color: convert_slice_to_array(element_color),
            drawn_line_object_denotation_shift,

            surface_default_color: convert_slice_to_array(surface_default_color),
            surface_plate_props_color: convert_slice_to_array(surface_plate_props_color),

            selection_rectangle_stroke_color: selection_rectangle_stroke_color.to_string(),
            selection_rectangle_fill_color: selection_rectangle_fill_color.to_string(), 

            event_target: event_target.to_string(),
            selected_object_event_name: selected_object_event_name.to_string(),

            beam_section_orientation_line_length,
            beam_section_orientation_cap_height,
            beam_section_orientation_cap_width,
            beam_section_orientation_cap_base_points_number,
            beam_section_orientation_color: convert_slice_to_array(beam_section_orientation_color),

            surface_normal_line_length,
            surface_normal_cap_height,
            surface_normal_cap_width,
            surface_normal_cap_base_points_number,
            surface_normal_color: convert_slice_to_array(surface_normal_color),

            concentrated_load_line_length,
            concentrated_load_cap_height,
            concentrated_load_cap_width,
            concentrated_load_cap_base_points_number,
            concentrated_load_color: convert_slice_to_array(concentrated_load_color),

            uniformly_distributed_line_load_line_length,
            uniformly_distributed_line_load_cap_height,
            uniformly_distributed_line_load_cap_width,
            uniformly_distributed_line_load_cap_base_points_number,
            uniformly_distributed_line_load_color: convert_slice_to_array(uniformly_distributed_line_load_color),
            number_of_uniformly_distributed_line_load_arrows,

            uniformly_distributed_surface_load_line_length,
            uniformly_distributed_surface_load_cap_height,
            uniformly_distributed_surface_load_cap_width,
            uniformly_distributed_surface_load_cap_base_points_number,
            uniformly_distributed_surface_load_color: convert_slice_to_array(uniformly_distributed_surface_load_color),
            number_of_uniformly_distributed_surface_load_arrows,

            point_boundary_condition_cap_height,
            point_boundary_condition_cap_width,
            point_boundary_condition_cap_base_point_number,
            point_boundary_condition_color: convert_slice_to_array(point_boundary_condition_color),

            global_mesh_seed_color: convert_slice_to_array(global_mesh_seed_color),
            local_mesh_seed_color: convert_slice_to_array(local_mesh_seed_color),

            symbols_min_line_length,
            symbols_min_cap_height,
            symbols_min_cap_width,
            symbols_max_line_length,
            symbols_max_cap_height,
            symbols_max_cap_width,
            symbols_cap_base_points_number,

            color_bar_shift_x,
            color_bar_y_bottom,
            color_bar_y_top,
            color_bar_width,
            color_bar_min_color: convert_slice_to_array(color_bar_min_color),
            color_bar_max_color: convert_slice_to_array(color_bar_max_color),

            color_bar_caption_shift_x,
            color_bar_caption_header_shift_y,
            color_bar_caption_component_shift_y,
            color_bar_caption_extreme_value_shift_x,

            local_axis_line_length,
            local_axis_cap_height,
            local_axis_cap_width,
            local_axis_cap_base_points_number,
            local_axis_r_color: convert_slice_to_array(local_axis_r_color),
            local_axis_s_color: convert_slice_to_array(local_axis_s_color),
            local_axis_t_color: convert_slice_to_array(local_axis_t_color),

            plate_scale_for_load_arrows,
        }
    }
}
